export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const CHECK_AUTH = 'CHECK_AUTH'
export const LOADING = 'LOADING'
export const LOCAL_LOADING = 'LOCAL_LOADING'
export const LOAD_APPS = 'LOAD_APPS'
export const CREATE_APP = 'CREATE_APP'
export const LOAD_UNITS = 'LOAD_UNITS'